### PR TITLE
[WIP] Make symbols work with percy.io

### PR DESCRIPTION
**Pull request by kiwiupover**
For the test environment move the symbols div into `#ember-testing` div
ember-percy copies the dom from `#ember-testing`
to take a snapshot of the test.

@fotinakis

### CODE REVIEW

**Comment by jherdman** [comment]
@kiwiupover are you able to rebase this PR?

**Comment by jherdman** [comment]
@kiwiupover do you still need this PR or any help to finish it off?

**Comment by kiwiupover** [comment]
@jherdman Let me check today.

**Comment by elidupuis** [comment]
I just ran into this issue trying to configure Percy in our app as well. Any chance to push this PR over the finish line?

**Comment by jherdman** [comment]
I'd love to see a test for this. It's not really clear if it works. Perhaps the function body of `contentFor` can be extracted into a function that can be unit tested?

**Comment by jherdman** [comment]
@kiwiupover any qualms with me taking over this PR?

**Comment by jherdman** [comment]
Closing in favour of #215 . Apologies for sleeping on this @kiwiupover

**Pull request closed without merging**
