### PR TITLE
Update Ember-CLI and add tests/dummy/public

### PR DESCRIPTION
**Pull request by rwwagner90**
I updated to Ember-CLI 2.17.1 and ran the related blueprints with `ember init`.

I also think I have a partial solution for https://github.com/ivanvotti/ember-svg-jar/issues/29

I added a check in src/index.js like:

```js
if(isAddon) {
  defaultOpts.sourceDirs.push('tests/dummy/public');
}
```

So we should be automatically adding `tests/dummy/public` to the directories we look through, if you are inside an addon.

I tried linking locally to an addon to test, but when I ran `ember s` the addon could not access http://localhost:4200/ember-svg-jar/index.html so I am not 100% sure if this works or not, but I think it should. I was able to see that `isAddon` was evaluating correctly and pushing to the source directories.

### CODE REVIEW

**Comment by rwwagner90** [comment]
It looks like there are issues with Ember 1.10.0 for some reason. Can we just support 1.13+? Those versions are really old now, so not sure how important it is to you to support them.

**Comment by ivanvotti** [comment]
That's cool. Thank you. I'll take a look at it.

**Comment by rwwagner90** [comment]
I went ahead and updated support to be  >= 1.13.13.

**Comment by rwwagner90** [comment]
@ivanvotti any questions for me or anything I can do to help get this merged? Happy to help any way I can!

**Comment by rwwagner90** [comment]
Thanks for merging! Would you mind releasing as well?

**Comment by ivanvotti** [comment]
Sure. I'll probably do it today.

**Pull request merged**
